export const menuByRole = {
  ADMIN: [
    { labelKey: "routes.dashboard", path: "/" },
    { labelKey: "routes.clients", path: "/clientes" },
    { labelKey: "routes.properties", path: "/propiedades" },
    { labelKey: "routes.categories", path: "/categorias-servicio" },
    { labelKey: "routes.services", path: "/servicios" },
    { labelKey: "routes.users", path: "/usuarios" },
    { labelKey: "routes.employees", path: "/empleados" },
    { labelKey: "routes.schedules", path: "/programaciones" },
    { labelKey: "routes.quotes", path: "/cotizaciones" },
    { labelKey: "routes.orders", path: "/ordenes" },
    { labelKey: "routes.payments", path: "/pagos" },
    { labelKey: "routes.credits", path: "/creditos" },
    { labelKey: "routes.collections", path: "/cobranza" },
    { labelKey: "routes.agendaToday", path: "/agenda/hoy" },
    { labelKey: "routes.agendaWeekly", path: "/agenda/semanal" },
    { labelKey: "routes.agendaMonthly", path: "/agenda/mensual" },
    { labelKey: "routes.security", path: "/seguridad" },
    { labelKey: "routes.audit", path: "/auditoria" },
  ],
  SUPERVISOR: [
    { labelKey: "routes.dashboard", path: "/" },
    { labelKey: "routes.clients", path: "/clientes" },
    { labelKey: "routes.properties", path: "/propiedades" },
    { labelKey: "routes.categories", path: "/categorias-servicio" },
    { labelKey: "routes.services", path: "/servicios" },
    { labelKey: "routes.employees", path: "/empleados" },
    { labelKey: "routes.schedules", path: "/programaciones" },
    { labelKey: "routes.quotes", path: "/cotizaciones" },
    { labelKey: "routes.orders", path: "/ordenes" },
    { labelKey: "routes.payments", path: "/pagos" },
    { labelKey: "routes.credits", path: "/creditos" },
    { labelKey: "routes.collections", path: "/cobranza" },
    { labelKey: "routes.agendaToday", path: "/agenda/hoy" },
    { labelKey: "routes.agendaWeekly", path: "/agenda/semanal" },
    { labelKey: "routes.agendaMonthly", path: "/agenda/mensual" },
    { labelKey: "routes.security", path: "/seguridad" },
    { labelKey: "routes.audit", path: "/auditoria" },
  ],
  OPERADOR: [
    { labelKey: "routes.dashboard", path: "/" },
    { labelKey: "routes.clients", path: "/clientes" },
    { labelKey: "routes.properties", path: "/propiedades" },
    { labelKey: "routes.orders", path: "/ordenes" },
    { labelKey: "routes.agendaToday", path: "/agenda/hoy" },
    { labelKey: "routes.agendaWeekly", path: "/agenda/semanal" },
    { labelKey: "routes.agendaMonthly", path: "/agenda/mensual" },
    { labelKey: "routes.security", path: "/seguridad" },
  ],
  COBRADOR: [
    { labelKey: "routes.dashboard", path: "/" },
    { labelKey: "routes.clients", path: "/clientes" },
    { labelKey: "routes.payments", path: "/pagos" },
    { labelKey: "routes.credits", path: "/creditos" },
    { labelKey: "routes.collections", path: "/cobranza" },
    { labelKey: "routes.agendaToday", path: "/agenda/hoy" },
    { labelKey: "routes.agendaWeekly", path: "/agenda/semanal" },
    { labelKey: "routes.agendaMonthly", path: "/agenda/mensual" },
    { labelKey: "routes.security", path: "/seguridad" },
  ],
};
